# Cloud SQL for PostgreSQL — ONE instance, two databases (UAT + PROD), separate users.
# Cloud Run reaches it via the Cloud SQL connector (socket), so no public network access
# is required. (Passwords are generated by TF and live in the access-controlled state
# bucket; the DATABASE_URL secrets are consumed by Cloud Run at runtime.)

resource "google_project_service" "sqladmin" {
  service            = "sqladmin.googleapis.com"
  disable_on_destroy = false
}

resource "google_sql_database_instance" "main" {
  name             = "claudex-db"
  database_version = "POSTGRES_15"
  region           = var.region
  depends_on       = [google_project_service.sqladmin]

  settings {
    tier              = "db-g1-small"
    edition           = "ENTERPRISE"
    availability_type = "ZONAL"
    disk_size         = 10
    disk_type         = "PD_SSD"
    disk_autoresize   = true

    ip_configuration {
      ipv4_enabled = true # reachable only via the Cloud SQL connector (IAM-authed); no authorized networks
    }
    backup_configuration {
      enabled = true
    }
  }

  deletion_protection = true
}

locals {
  envs = toset(["uat", "prod"])
}

resource "google_sql_database" "db" {
  for_each = local.envs
  name     = "claudex_${each.key}"
  instance = google_sql_database_instance.main.name
}

resource "random_password" "db" {
  for_each = local.envs
  length   = 32
  special  = false
}

resource "google_sql_user" "user" {
  for_each = local.envs
  name     = "claudex_${each.key}"
  instance = google_sql_database_instance.main.name
  password = random_password.db[each.key].result
}

# DATABASE_URL per env (Prisma + Cloud Run via the Cloud SQL unix socket).
resource "google_secret_manager_secret" "dburl" {
  for_each  = local.envs
  secret_id = "claudex-dburl-${each.key}"
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "dburl" {
  for_each    = local.envs
  secret      = google_secret_manager_secret.dburl[each.key].id
  secret_data = "postgresql://claudex_${each.key}:${random_password.db[each.key].result}@localhost/claudex_${each.key}?host=/cloudsql/${google_sql_database_instance.main.connection_name}&sslmode=disable"
}

output "instance_connection_name" {
  value = google_sql_database_instance.main.connection_name
}
